### ISSUE TITLE
Why no { Component } import?

### ISSUE THREAD

**Issue by olegafx** [vslinko/babel-react-require#1]
I looked at your example and saw 1 strange thing: where is `Component` import? Extending React.Component is pretty common case, no?

```javascript
import React from 'react'

export default class Component {
  render() {
    /* this part will be transpiled by babel itself as usual */
    return React.createElement('div')
  }
}
```

**Comment by vslinko** [comment]
If you want to extend Component you should import it by yourself.
This plugin only about `createElement` and JSX.

**Comment by vslinko** [comment]
Added some note in README.

**Comment by vyorkin** [comment]
@olegafx If you still need it, you can implement it yourself, its not that hard.
Here is an example (for babel v5.x):
```
        var reactImportDeclaration = t.importDeclaration([
          t.importDefaultSpecifier(t.identifier('React')),
          t.importSpecifier(t.identifier('Component'), t.identifier('Component')),
          t.importSpecifier(t.identifier('PropTypes'), t.identifier('PropTypes'))
        ], t.literal('react'))
```

take a look at the babel source, [here](https://github.com/babel/babel/blob/5.x/packages/babel/src/transformation/modules/common.js#L105) and [here](https://github.com/babel/babel/blob/5.x/packages/babel/src/transformation/modules/common.js#L61)
